pipeline {
  agent any
  tools { maven 'MAVEN_3_9' }                 // exact ca în Manage Jenkins → Tools
  options { timestamps(); timeout(time: 20, unit: 'MINUTES') }

  stages {
    stage('Checkout')      { steps { checkout scm } }
    stage('Build & Test')  { steps { sh 'mvn -B -ntp clean package' } }
    stage('Archive') {
      steps {
        archiveArtifacts artifacts: 'target/*.jar, target/*.war', fingerprint: true
        junit '**/target/surefire-reports/*.xml'
      }
    }
  }
}
